find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBFLAC *flac* include lib)

SET(LIBFLAC_FOUND FALSE)
SET(LIBFLACPP_FOUND FALSE)

Find_Path(LIBFLAC_INCLUDE_DIR
	FLAC/all.h
	/usr/include/ /usr/local/include/
	${LIBFLAC_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBFLAC_LIBRARY
	FLAC
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)

IF(LIBFLAC_INCLUDE_DIR AND LIBFLAC_LIBRARY)
	SET(LIBFLAC_FOUND TRUE)
	MESSAGE(STATUS "Found flac library")
ENDIF(LIBFLAC_INCLUDE_DIR AND LIBFLAC_LIBRARY)

Find_Path(LIBFLACPP_INCLUDE_DIR
	FLAC++/all.h
	/usr/include/ /usr/local/include/
	${LIBFLAC_INCLUDE_DIR}
	${LIBFLAC_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBFLACPP_LIBRARY
	FLAC++
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)

IF(LIBFLACPP_INCLUDE_DIR AND LIBFLACPP_LIBRARY)
	SET(LIBFLACPP_FOUND TRUE)
	MESSAGE(STATUS "Found flac++ library")
ENDIF(LIBFLACPP_INCLUDE_DIR AND LIBFLACPP_LIBRARY)
