find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBFLAC *flac* include lib)

SET(LIBFLAC_FOUND FALSE)
SET(LIBFLAC_DEBUG_FOUND FALSE)
SET(LIBFLACPP_FOUND FALSE)
SET(LIBFLACPP_DEBUG_FOUND FALSE)

Find_Path(LIBFLAC_INCLUDE_DIR
	FLAC/all.h
	/usr/include/ /usr/local/include/
	${LIBFLAC_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBFLAC_LIBRARY
	FLAC
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBFLAC_DEBUG_LIBRARY
	FLACd
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)

IF(NOT MSVC) # Assume non-MSVC compilers don't care about different runtimes
	SET(LIBFLAC_DEBUG_LIBRARY ${LIBFLAC_LIBRARY})
ENDIF(NOT MSVC)

IF(LIBFLAC_INCLUDE_DIR AND LIBFLAC_LIBRARY AND LIBFLAC_DEBUG_LIBRARY)
	SET(LIBFLAC_FOUND TRUE)
	SET(LIBFLAC_DEBUG_FOUND TRUE)
	MESSAGE(STATUS "Found flac library")
ENDIF(LIBFLAC_INCLUDE_DIR AND LIBFLAC_LIBRARY AND LIBFLAC_DEBUG_LIBRARY)

Find_Path(LIBFLACPP_INCLUDE_DIR
	FLAC++/all.h
	/usr/include/ /usr/local/include/
	${LIBFLAC_INCLUDE_DIR}
	${LIBFLAC_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBFLACPP_LIBRARY
	FLAC++
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)


Find_Library(LIBFLACPP_DEBUG_LIBRARY
	FLAC++d
	/usr/lib /usr/local/lib
	${LIBFLAC_EXTRALIB_LIBRARY_PATHS}
)

IF(NOT MSVC) # Assume non-MSVC compilers don't care about different runtimes
	SET(LIBFLACPP_DEBUG_LIBRARY ${LIBFLACPP_LIBRARY})
ENDIF(NOT MSVC)

IF(LIBFLACPP_INCLUDE_DIR AND LIBFLACPP_LIBRARY AND LIBFLACPP_DEBUG_LIBRARY)
	SET(LIBFLACPP_FOUND TRUE)
	SET(LIBFLACPP_DEBUG_FOUND TRUE)
	MESSAGE(STATUS "Found flac++ library")
ENDIF(LIBFLACPP_INCLUDE_DIR AND LIBFLACPP_LIBRARY AND LIBFLACPP_DEBUG_LIBRARY)
