SET(LIBSIDPLAY2_FOUND FALSE)
SET(LIBSIDPLAY2_DEBUG_FOUND FALSE)
SET(LIBSIDPLAY2_RESID_BUILDER_FOUND FALSE)
SET(LIBSIDPLAY2_RESID_BUILDER_DEBUG_FOUND FALSE)

find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBSIDPLAY2 *sidplay* include lib)

Find_Path(LIBSIDPLAY2_INCLUDE_DIR
	NAMES sidplay/sidplay2.h
	PATHS /usr/include /usr/local/include ${LIBSIDPLAY2_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBSIDPLAY2_LIBRARY
	NAMES sidplay2
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY2_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBSIDPLAY2_DEBUG_LIBRARY
	NAMES sidplay2d
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY2_EXTRALIB_LIBRARY_PATHS}
)

Find_Path(LIBSIDPLAY2_RESID_BUILDER_INCLUDE_DIR
	NAMES sidplay/builders/resid.h
	PATHS /usr/include /usr/local/include ${LIBSIDPLAY2_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBSIDPLAY2_RESID_BUILDER_LIBRARY
	NAMES resid-builder
	PATHS /usr/lib/sidplay/builders /usr/local/lib/sidplay/builders ${LIBSIDPLAY2_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBSIDPLAY2_RESID_BUILDER_DEBUG_LIBRARY
	NAMES resid-builderd
	PATHS /usr/lib/sidplay/builders /usr/local/lib/sidplay/builders ${LIBSIDPLAY2_EXTRALIB_LIBRARY_PATHS}
)

IF(NOT MSVC) # Assume non-MSVC compilers don't care about different runtimes
	SET(LIBSIDPLAY2_DEBUG_LIBRARY ${LIBSIDPLAY2_LIBRARY})
	SET(LIBSIDPLAY2_RESID_BUILDER_DEBUG_LIBRARY ${LIBSIDPLAY2_RESID_BUILDER_LIBRARY})
ENDIF(NOT MSVC)

IF(LIBSIDPLAY2_INCLUDE_DIR AND LIBSIDPLAY2_LIBRARY AND LIBSIDPLAY2_DEBUG_LIBRARY AND LIBSIDPLAY2_RESID_BUILDER_INCLUDE_DIR AND LIBSIDPLAY2_RESID_BUILDER_LIBRARY AND LIBSIDPLAY2_RESID_BUILDER_DEBUG_LIBRARY)
	SET(LIBSIDPLAY2_FOUND TRUE)
	SET(LIBSIDPLAY2_DEBUG_FOUND TRUE)
	SET(LIBSIDPLAY2_RESID_BUILDER_FOUND TRUE)
	SET(LIBSIDPLAY2_RESID_BUILDER_DEBUG_FOUND TRUE)
	MESSAGE(STATUS "Found Sidplay library")
ENDIF(LIBSIDPLAY2_INCLUDE_DIR AND LIBSIDPLAY2_LIBRARY AND LIBSIDPLAY2_DEBUG_LIBRARY AND LIBSIDPLAY2_RESID_BUILDER_INCLUDE_DIR AND LIBSIDPLAY2_RESID_BUILDER_LIBRARY AND LIBSIDPLAY2_RESID_BUILDER_DEBUG_LIBRARY)
