BUFFERNAME="`echo ${1} | sed -e 's:.*/::' -e 's:\..*::'`_glade_definition"
P="`echo ${0} | sed 's:\(.*/\)\([^/]*\)$:\1:'`"
FILE="`echo ${1} | sed \"s:$P::\"`"
echo -en "/**\n * NOTE: This file is autogenerated, DO NOT EDIT THIS FILE,\n * EDIT ${FILE} INSTEAD!\n */\n\n" > ${2}
INCLUDEGUARD="`echo ${BUFFERNAME} | tr '[:lower:]' '[:upper:]'`_H"
echo -en "#ifndef ${INCLUDEGUARD}\n#define ${INCLUDEGUARD}\n" >> ${2}
echo "#ifdef __INIT_VARS__" >> ${2}
echo "char ${BUFFERNAME}[] =" >> ${2}
cat ${1} | sed s:\\\\:\\\\\\\\:g | sed s:\":\\\\\":g | sed s:$:\": | sed s:^:\": >> ${2}
echo ";" >> ${2}
echo "int ${BUFFERNAME}_size = sizeof(${BUFFERNAME});" >> ${2}
echo "#else" >> ${2}
echo "extern char ${BUFFERNAME}[];" >> ${2}
echo "extern int ${BUFFERNAME}_size;" >> ${2}
echo "#endif" >> ${2}
echo -en "#endif // ${INCLUDEGUARD}\n" >> ${2}
