BUFFERNAME="`echo ${1} | sed -e 's:.*/::' -e 's:\..*::'`_glade_definition"
echo -en "/**\n * NOTE: This file is autogenerated, DO NOT EDIT THIS FILE,\n * EDIT ${1} INSTEAD!\n */" > ${2}
echo "char ${BUFFERNAME}[] =" >> ${2}
cat ${1} | sed s:\\\\:\\\\\\\\:g | sed s:\":\\\\\":g | sed s:$:\": | sed s:^:\": >> ${2}
echo ";" >> ${2}
echo "int ${BUFFERNAME}_size = sizeof(${BUFFERNAME});" >> ${2}

