SET(LIBFAAD2_FOUND FALSE)

find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBFAAD2 *faad* include lib)

Find_Path(LIBFAAD2_INCLUDE_DIR
	NAMES faad.h
	PATHS /usr/include /usr/local/include ${LIBFAAD2_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBFAAD2_LIBRARY
	NAMES faad
	PATHS /usr/lib /usr/local/lib ${LIBFAAD2_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBFAAD2_DEBUG_LIBRARY
	NAMES faadd
	PATHS /usr/lib /usr/local/lib ${LIBFAAD2_EXTRALIB_LIBRARY_PATHS}
)

IF(NOT MSVC) # Assume non-MSVC compilers don't care about different runtimes
	SET(LIBFAAD2_DEBUG_LIBRARY ${LIBFAAD2_LIBRARY})
ENDIF(NOT MSVC)

SET(LIBFAAD2_FOUND FALSE)
SET(LIBFAAD2_DEBUG_FOUND FALSE)
IF(LIBFAAD2_INCLUDE_DIR AND LIBFAAD2_LIBRARY AND LIBFAAD2_DEBUG_LIBRARY)
	SET(LIBFAAD2_FOUND TRUE)
	SET(LIBFAAD2_DEBUG_FOUND TRUE)
	MESSAGE(STATUS "Found faad2 library")
ENDIF(LIBFAAD2_INCLUDE_DIR AND LIBFAAD2_LIBRARY AND LIBFAAD2_DEBUG_LIBRARY)
