SET(LIBSIDPLAY_FOUND FALSE)
SET(LIBSIDPLAY_DEBUG_FOUND FALSE)
SET(LIBSIDPLAY_RESID_BUILDER_FOUND FALSE)
SET(LIBSIDPLAY_RESID_BUILDER_DEBUG_FOUND FALSE)

find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBSIDPLAY *sidplay* include lib)

Find_Path(LIBSIDPLAY_INCLUDE_DIR
	NAMES sidplay/sidplay2.h
	PATHS /usr/include /usr/local/include ${LIBSIDPLAY_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBSIDPLAY_LIBRARY
	NAMES sidplay
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBSIDPLAY_DEBUG_LIBRARY
	NAMES sidplayd
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY_EXTRALIB_LIBRARY_PATHS}
)

Find_Path(LIBSIDPLAY_RESID_BUILDER_INCLUDE_DIR
	NAMES sidplay/builders/resid.h
	PATHS /usr/include /usr/local/include ${LIBSIDPLAY_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBSIDPLAY_RESID_BUILDER_LIBRARY
	NAMES resid_builder
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY_EXTRALIB_LIBRARY_PATHS}
)

Find_Library(LIBSIDPLAY_RESID_BUILDER_DEBUG_LIBRARY
	NAMES resid_builderd
	PATHS /usr/lib /usr/local/lib ${LIBSIDPLAY_EXTRALIB_LIBRARY_PATHS}
)

IF(NOT MSVC) # Assume non-MSVC compilers don't care about different runtimes
	SET(LIBSIDPLAY_DEBUG_LIBRARY ${LIBSIDPLAY_LIBRARY})
	SET(LIBSIDPLAY_RESID_BUILDER_LIBRARY ${LIBSIDPLAY_RESID_BUILDER_DEBUG_LIBRARY})
ENDIF(NOT MSVC)

IF(LIBSIDPLAY_INCLUDE_DIR AND LIBSIDPLAY_LIBRARY AND LIBSIDPLAY_DEBUG_LIBRARY AND LIBSIDPLAY_RESID_BUILDER_INCLUDE_DIR AND LIBSIDPLAY_RESID_BUILDER_LIBRARY AND LIBSIDPLAY_RESID_BUILDER_DEBUG_LIBRARY)
	SET(LIBSIDPLAY_FOUND TRUE)
	SET(LIBSIDPLAY_DEBUG_FOUND TRUE)
	SET(LIBSIDPLAY_RESID_BUILDER_FOUND TRUE)
	SET(LIBSIDPLAY_RESID_BUILDER_DEBUG_FOUND TRUE)
	MESSAGE(STATUS "Found Sidplay library")
ENDIF(LIBSIDPLAY_INCLUDE_DIR AND LIBSIDPLAY_LIBRARY AND LIBSIDPLAY_DEBUG_LIBRARY AND LIBSIDPLAY_RESID_BUILDER_INCLUDE_DIR AND LIBSIDPLAY_RESID_BUILDER_LIBRARY AND LIBSIDPLAY_RESID_BUILDER_DEBUG_LIBRARY)
