find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBSAMPLERATE *samplerate* include lib)

SET(LIBSAMPLERATE_FOUND FALSE)

Find_Path(LIBSAMPLERATE_INCLUDE_DIR
	samplerate.h
	/usr/include /usr/local/include
	${LIBSAMPLERATE_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBSAMPLERATE_LIBRARY
	libsamplerate
	/usr/lib /usr/local/lib
	${LIBSAMPLERATE_EXTRALIB_LIBRARY_PATHS}
)

IF(LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARY)
	SET(LIBSAMPLERATE_FOUND TRUE)
	MESSAGE(STATUS "Found samplerate library (libsamplerate)")
ENDIF(LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARY)
