find_package(ExtraLibDir)

FIND_LIB_IN_EXTRALIBS(LIBDUMB *dumb* include lib)

SET(LIBDUMB_FOUND FALSE)

Find_Path(LIBDUMB_INCLUDE_DIR
	dumb.h
	/usr/include /usr/local/include
	${LIBSAMPLERATE_EXTRALIB_INCLUDE_PATHS}
)

Find_Library(LIBDUMB_LIBRARY
	dumb
	/usr/lib /usr/local/lib
	${LIBSAMPLERATE_EXTRALIB_LIBRARY_PATHS}
)

IF(LIBDUMB_INCLUDE_DIR AND LIBDUMB_LIBRARY)
	SET(LIBDUMB_FOUND TRUE)
	MESSAGE(STATUS "Found dumb library (libdumb)")
ENDIF(LIBDUMB_INCLUDE_DIR AND LIBDUMB_LIBRARY)
